### ISSUE TITLE
Error messages when running

### ISSUE THREAD

**Issue by brentrahn** [SpaceK33z/plex2netflix#18]
I'm sure I'm just doing something wrong, but this is the output I get when I try to run plex2netflix. Any help would be greatly appreciated. 

NodeJS v4.2.6

/usr/local/lib/node_modules/plex2netflix/lib/index.js:19
    let result = Promise.resolve();
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/plex2netflix/lib/cli.js:2:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by SpaceK33z** [comment]
Ah, I kinda forgot to test in Node v4. On Node v6 this will work correctly.

**Comment by brentrahn** [comment]
Works now. Thanks!
